designers = {}
designers["20thCenturyFaux"] = {"champions": []}
designers["Aether"] = {"champions": []}
designers["AzuBK"] = {"champions": []}
designers["BeatPunchBeef"] = {"champions": []}
designers["BelugaWhale"] = {"champions": []}
designers["Brackhar"] = {"champions": []}
designers["Britanny Gleiter"] = {"champions": []}
designers["CertainlyT"] = {"champions": []}
designers["Cheeky Git"] = {"champions": []}
designers["Classick"] = {"champions": []}
designers["Coronach"] = {"champions": []}
designers["EndlessPillows"] = {"champions": []}
designers["Ezreal"] = {"champions": []}
designers["fantasyworld"] = {"champions": []}
designers["Fearless"] = {"champions": []}
designers["FeralPony"] = {"champions": []}
designers["Iniquitee"] = {"champions": []}
designers["Issfire"] = {"champions": []}
designers["jinxylord"] = {"champions": []}
designers["Geeves"] = {"champions": []}
designers["GMang"] = {"champions": []}
designers["Guinsoo"] = {"champions": []}
designers["Harrow"] = {"champions": []}
designers["Hephastopheles"] = {"champions": []}
designers["Jag"] = {"champions": []}
designers["JuliusEjsing"] = {"champions": []}
designers["Kevin Leroy"] = {"champions": []}
designers["ManEolfAxeBoss"] = {"champions": []}
designers["Mark Khalil"] = {"champions": []}
designers["Meddler"] = {"champions": []}
designers["Neurocat"] = {"champions": []}
designers["NoopMoney"] = {"champions": []}
designers["Phroxzon"] = {"champions": []}
designers["Rabid Llama"] = {"champions": []}
designers["Repertoir"] = {"champions": []}
designers["ricklessabandon"] = {"champions": []}
designers["rjcombo"] = {"champions": []}
designers["Scarizard"] = {"champions": []}
designers["Scruffy"] = {"champions": []}
designers["Shadowstorm"] = {"champions": []}
designers["Shrieve"] = {"champions": []}
designers["Shurelia"] = {"champions": []}
designers["Skribbles"] = {"champions": []}
designers["Stashu"] = {"champions": []}
designers["SolCrushed"] = {"champions": []}
designers["Sotere"] = {"champions": []}
designers["subninja"] = {"champions": []}
designers["Squad5"] = {"champions": []}
designers["Statikk"] = {"champions": []}
designers["SurpriseNDelight"] = {"champions": []}
designers["TheBravoRay"] = {"champions": []}
designers["Tom Robbins"] = {"champions": []}
designers["Volty"] = {"champions": []}
designers["Wav3break"] = {"champions": []}
designers["Wendigo"] = {"champions": []}
designers["Wrekz"] = {"champions": []}
designers["Xenogenic"] = {"champions": []}
designers["Xypherous"] = {"champions": []}
designers["ZenonTheStoic"] = {"champions": []}
designers["Zileas"] = {"champions": []}

champions = {}
champions["Aatrox"] = {"designers": ["Classick", "Jag", "ricklessabandon"]}
champions["Ahri"] = {"designers": ["Ezreal", "Coronach", "ricklessabandon"]}
champions["Akali"] = {"designers": ["Coronach", "CertainlyT", "ricklessabandon"]}
champions["Alistar"] = {"designers": ["Guinsoo"]}
champions["Anivia"] = {"designers": ["Brackhar", "Guinsoo"]}
champions["Annie"] = {"designers": ["Ezreal", "Guinsoo", "Zileas", "BelugaWhale"]}
champions["Ashe"] = {"designers": ["Ezreal", "Guinsoo", "Repertoir"]}
champions["AurelionSol"] = {"designers": ["Rabid Llama"]}
champions["Azir"] = {"designers": ["Wav3break", "ZenonTheStoic"]}
champions["Bard"] = {"designers": ["Rabid Llama"]}
champions["Blitzcrank"] = {"designers": ["Ezreal"]}
champions["Brand"] = {"designers": ["Coronach", "20thCenturyFaux"]}
champions["Braum"] = {"designers": ["Wrekz"]}
champions["Caitlyn"] = {"designers": ["Ezreal", "CertainlyT"]}
champions["Camille"] = {"designers": ["Jag"]}
champions["Cassiopeia"] = {"designers": ["Brackhar", "Stashu", "Repertoir"]}
champions["Chogath"] = {"designers": ["Ezreal", "AzuBK", "Guinsoo", "ManEolfAxeBoss"]}
champions["Corki"] = {"designers": ["Statikk", "Coronach"]}
champions["Darius"] = {"designers": ["CertainlyT", "Statikk"]}
champions["Diana"] = {"designers": ["Volty"]}
champions["DrMundo"] = {"designers": ["fantasyworld"]}
champions["Ekko"] = {"designers": ["jinxylord"]}
champions["Elise"] = {"designers": ["Coronach", "Meddler", "Kevin Leroy"]}
champions["Evelynn"] = {"designers": ["Guinsoo", "Stashu"]}
champions["Ezreal"] = {"designers": ["Mark Khalil", "Ezreal"]}
champions["Fiora"] = {"designers": ["Volty", "Stashu"]}
champions["Fizz"] = {"designers": ["Xypherous", "Shrieve", "Neurocat"]}
champions["Galio"] = {"designers": ["rjcombo", "SolCrushed"]}
champions["Gangplank"] = {"designers": ["Statikk", "SolCrushed"]}
champions["Garen"] = {"designers": ["Geeves", "Repertoir"]}
champions["Gnar"] = {"designers": ["jinxylord", "Meddler"]}
champions["Gragas"] = {"designers": ["Geeves", "SolCrushed"]}
champions["Graves"] = {"designers": ["FeralPony", "CertainlyT", "Kevin Leroy"]}
champions["Hecarim"] = {"designers": ["FeralPony"]}
champions["Heimerdinger"] = {"designers": ["Ezreal", "Phroxzon", "20thCenturyFaux"]}
champions["Illaoi"] = {"designers": ["BeatPunchBeef"]}
champions["Irelia"] = {"designers": ["Ezreal", "SolCrushed"]}
champions["Ivern"] = {"designers": ["SurpriseNDelight", "Squad5", "Cheeky Git"]}
champions["Janna"] = {"designers": ["Brackhar"]}
champions["JarvanIV"] = {"designers": ["Ezreal"]}
champions["Jax"] = {"designers": ["Ezreal", "FeralPony"]}
champions["Jayce"] = {"designers": ["FeralPony", "Hephastopheles", "JuliusEjsing"]}
champions["Jhin"] = {"designers": ["jinxylord", "Squad5"]}
champions["Jinx"] = {"designers": ["jinxylord", "Kevin Leroy"]}
champions["Kaisa"] = {"designers": ["Jag"]}
champions["Kalista"] = {"designers": ["CertainlyT"]}
champions["Karma"] = {"designers": ["Coronach", "Scarizard"]}
champions["Karthus"] = {"designers": ["Guinsoo"]}
champions["Kassadin"] = {"designers": ["Ezreal", "Statikk"]}
champions["Katarina"] = {"designers": ["Coronach", "BelugaWhale"]}
champions["Kayle"] = {"designers": ["Ezreal", "Guinsoo", "Coronach", "Shurelia"]}
champions["Kayn"] = {"designers": ["ZenonTheStoic"]}
champions["Kennen"] = {"designers": ["Geeves"]}
champions["Khazix"] = {"designers": ["Volty", "BelugaWhale"]}
champions["Kindred"] = {"designers": ["Wrekz", "Wav3break"]}
champions["Kled"] = {"designers": ["Harrow"]}
champions["KogMaw"] = {"designers": ["Ezreal", "Repertoir"]}
champions["Leblanc"] = {"designers": ["Coronach", "20thCenturyFaux", "AzuBK"]}
champions["LeeSin"] = {"designers": ["Coronach"]}
champions["Leona"] = {"designers": ["Volty"]}
champions["Lissandra"] = {"designers": ["Meddler"]}
champions["Lucian"] = {"designers": ["ZenonTheStoic"]}
champions["Lulu"] = {"designers": ["Xypherous"]}
champions["Lux"] = {"designers": ["Shurelia"]}
champions["Malphite"] = {"designers": ["Coronach"]}
champions["Malzahar"] = {"designers": ["Ezreal", "Repertoir"]}
champions["Maokai"] = {"designers": ["Volty", "BelugaWhale"]}
champions["MasterYi"] = {"designers": ["Ezreal", "Shurelia"]}
champions["MissFortune"] = {"designers": ["Geeves", "Statikk", "Britanny Gleiter"]}
champions["Mordekaiser"] = {"designers": ["Coronach", "CertainlyT", "Guinsoo"]}
champions["Morgana"] = {"designers": ["Ezreal", "Guinsoo", "Brackhar"]}
champions["Nami"] = {"designers": ["Classick"]}
champions["Nasus"] = {"designers": ["Ezreal"]}
champions["Nautilus"] = {"designers": ["Xypherous"]}
champions["Nidalee"] = {"designers": ["Brackhar", "Repertoir", "Britanny Gleiter"]}
champions["Nocturne"] = {"designers": ["Ezreal"]}
# champions["Nunu"] = {"designers": ["Guinsoo", "Xenogenic"]}
champions["Olaf"] = {"designers": ["Coronach"]}
champions["Orianna"] = {"designers": ["Xypherous"]}
champions["Ornn"] = {"designers": ["Squad5"]}
champions["Pantheon"] = {"designers": ["Shurelia"]}
champions["Poppy"] = {"designers": ["Coronach", "SolCrushed"]}
champions["Pyke"] = {"designers": ["EndlessPillows"]}
champions["Quinn"] = {"designers": ["Volty", "Wendigo", "Repertoir", "Xenogenic", "Britanny Gleiter"]}
champions["Rakan"] = {"designers": ["BeatPunchBeef", "EndlessPillows"]}
champions["Rammus"] = {"designers": ["Ezreal", "Guinsoo", "Coronach"]}
champions["RekSai"] = {"designers": ["BeatPunchBeef", "Sotere"]}
champions["Renekton"] = {"designers": ["Xypherous"]}
champions["Rengar"] = {"designers": ["Classick", "Repertoir", "Scruffy", "jinxylord"]}
champions["Riven"] = {"designers": ["Xypherous", "Tom Robbins"]}
champions["Rumble"] = {"designers": ["FeralPony"]}
champions["Ryze"] = {"designers": ["Ezreal", "Guinsoo", "Brackhar", "Shurelia", "Repertoir"]}
champions["Sejuani"] = {"designers": ["Volty", "SolCrushed"]}
champions["Shaco"] = {"designers": ["Guinsoo", "20thCenturyFaux"]}
champions["Shen"] = {"designers": ["Guinsoo", "GMang"]}
champions["Shyvana"] = {"designers": ["Coronach", "Wav3break", "Aether"]}
champions["Singed"] = {"designers": ["Ezreal", "Guinsoo"]}
champions["Sion"] = {"designers": ["Ezreal", "Scruffy"]}
champions["Sivir"] = {"designers": ["Ezreal", "Guinsoo", "Statikk"]}
champions["Skarner"] = {"designers": ["Volty", "Repertoir"]}
champions["Sona"] = {"designers": ["Ezreal", "Fearless", "Shurelia"]}
champions["Soraka"] = {"designers": ["Guinsoo"]}
champions["Swain"] = {"designers": ["Coronach", "TheBravoRay", "Wav3break", "20thCenturyFaux"]}
champions["Syndra"] = {"designers": ["Meddler"]}
champions["TahmKench"] = {"designers": ["ZenonTheStoic"]}
champions["Taliyah"] = {"designers": ["ZenonTheStoic", "Shadowstorm", "Iniquitee"]}
champions["Talon"] = {"designers": ["Hephastopheles", "Stashu"]}
champions["Taric"] = {"designers": ["Brackhar", "Repertoir"]}
champions["Teemo"] = {"designers": ["Ezreal"]}
champions["Thresh"] = {"designers": ["CertainlyT"]}
champions["Tristana"] = {"designers": ["Ezreal"]}
champions["Trundle"] = {"designers": ["Geeves"]}
champions["Tryndamere"] = {"designers": ["Guinsoo"]}
champions["TwistedFate"] = {"designers": ["Guinsoo"]}
champions["Twitch"] = {"designers": ["Guinsoo"]}
champions["Udyr"] = {"designers": ["Coronach"]}
champions["Urgot"] = {"designers": ["Issfire", "Geeves", "Repertoir", "BelugaWhale"]}
champions["Varus"] = {"designers": ["Meddler"]}
champions["Vayne"] = {"designers": ["Volty"]}
champions["Veigar"] = {"designers": ["Coronach", "BelugaWhale"]}
champions["Velkoz"] = {"designers": ["subninja", "Repertoir", "BelugaWhale"]}
champions["Vi"] = {"designers": ["jinxylord", "Mark Khalil"]}
champions["Viktor"] = {"designers": ["Hephastopheles", "SolCrushed"]}
champions["Vladimir"] = {"designers": ["Ezreal", "Stashu"]}
champions["Volibear"] = {"designers": ["Volty"]}
champions["Warwick"] = {"designers": ["Ezreal", "CertainlyT", "NoopMoney"]}
champions["MonkeyKing"] = {"designers": ["Coronach"]}
champions["Xayah"] = {"designers": ["EndlessPillows", "BeatPunchBeef"]}
champions["Xerath"] = {"designers": ["Volty"]}
champions["XinZhao"] = {"designers": ["Geeves", "Xenogenic"]}
champions["Yasuo"] = {"designers": ["CertainlyT"]}
champions["Yorick"] = {"designers": ["Coronach", "SolCrushed", "Britanny Gleiter"]}
champions["Zac"] = {"designers": ["subninja", "Shrieve"]}
champions["Zed"] = {"designers": ["Hephastopheles", "CertainlyT", "Wav3break"]}
champions["Ziggs"] = {"designers": ["Meddler"]}
champions["Zilean"] = {"designers": ["Ezreal"]}
champions["Zoe"] = {"designers": ["CertainlyT"]}
champions["Zyra"] = {"designers": ["Skribbles", "CertainlyT", "Coronach", "20thCenturyFaux", "Britanny Gleiter"]}
